### ISSUE TITLE
一些tag建議

### ISSUE THREAD

**Issue by moon-jam** [dada878/CSES-Helper#4]
1. [Knight's Tour](https://cses.fi/problemset/task/1689)的tag應該錯了，`位元DP（Bitmask DP）`可能改成`剪枝/貪心（Warnsdorff's Algorithm）`或是再加`DFS回朔`會比較好
  <img width="897" alt="image" src="https://github.com/dada878/CSES-Helper/assets/54764038/6c6a1539-f1d9-4020-b9f6-a6eeab12d33e">

2. [Coin Collector](https://cses.fi/problemset/task/1686)這題希望可以加個`強連通分量（SCC）`   

3. [Distinct Routes](https://cses.fi/problemset/task/1711)這題希望可以加個`最大流（Flow）`

**Comment by dada878** [comment]
哈囉 Moon Jam，感謝你提供的建議，更改已經修改了上去了，幫我看一下這是不是你的意思。另外，如果有興趣的話，你也可以發 PR 修改哦！
